---
- name: This is playbook install packaes 
  hosts: webservers
  become: yes
  tasks: 
  - name: install packages
    yum:
      name: httpd
      state: installed
    notify: starting service 
  handlers:
  - name: starting service
    service: 
        name: httpd
        state: started
...
