---
- name: this playbook install httpd
  hosts: all
  become: yes
  tasks:
  - name: install packages httpd
    yum:
      name: httpd
      state: installed
  - name: starting service
    service:
         name: httpd
         state: started
...

