---
- name: This playbook install packages 
  hosts: all
  become: yes
  tasks:
  - name: install httpd packages
    yum:
      name: httpd
      state: installed
  
  - name: starting service
    service:
       name: httpd
       state: started
    
  - name: install packages apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: starting service 
    service: 
         name: apache2
         state: started
    when: ansible_os_family == "Debian"
  - name: copy the index.html file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0677
      owner: koneti

...
